CONFIG_PM=y
CONFIG_PM_DEVICE=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=120000
CONFIG_ZMK_IDLE_TIMEOUT=30000

CONFIG_LOG=n
CONFIG_SERIAL=n
CONFIG_USB_DEVICE_STACK=n

CONFIG_BT_MAX_CONN=1
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=24
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=40
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=500


CONFIG_ZMK_USB_LOGGING=n

CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
